Linkify for Hydrogen
element-hq/hydrogen-web pull request #345
Opened 2021-05-08 13:59 UTC by MidhunSureshR

Implements feature request #246.

2021-05-10 13:37 UTC, bwindels requested changes
This looks great, thank you!

A few comments about naming, and one about keeping the linkifier just about links, rather than also handling newlines. Other than that, looking great :+1:

2021-05-10 13:37 UTC, bwindels commented on src/domain/MessageObjectFormat.js
> +export class MessageObjectFormat {
I like the concept of this class, but the name is a bit implementation-detail-y. What about `MessageBody` or `MessageBodyBuilder`?

Also, can we put this and the linkifier in `src/domain/session/room/timeline` as it is specific to the timeline?

2021-05-10 13:37 UTC, bwindels commented on src/domain/Linkifier.js
> +    _addTextToMessage(text) {
This doesn't seem related to linkifying, I wonder if we should move the newline handling to `MessageObjectFormat`. So for every line `MessageObjectFormat` detects, it calls the linkifier with that line to split it up. Perhaps the `Linkifier` class can even be a `linkify` function given it has so little state, where apart from the text you pass in a `callback(isLink, text)` which `MessageObjectFormat` then translates into `insertText` (if `isLink` is `false`) or `insertLink` calls internally. Wdyt?

2021-05-10 13:37 UTC, bwindels commented on src/domain/session/room/timeline/tiles/TextTile.js
> +        let body = content && content.body;
I think the linkifier won't work if body is undefined here, so perhaps we can fall back to an empty string
```suggestion
        let body = content?.body || "";
```

2021-05-10 13:37 UTC, bwindels commented on src/domain/session/room/timeline/tiles/TextTile.js
> +    get messageFormat() {
I'd expect a format to be a format identifier like `html` or something ... not the actual message content. What about just calling this `body`?

2021-05-10 13:37 UTC, bwindels commented on src/platform/web/ui/session/room/timeline/TextMessageView.js
> +            const element = f({ obj: m, t: t });
perhaps don't create an extra object here, but just pass `m` and `t` as separate arguments? Otherwise looks great!

2021-05-10 13:37 UTC, bwindels commented on src/platform/web/ui/session/room/timeline/TextMessageView.js
> +        return {
this object can probably just exist as a variable at the module level so it doesn't get recreated every time `_formatFunction` is called.

2021-05-11 11:36 UTC, bwindels requested changes
Thank you for the changes!
A few more bits, we're close now :)

2021-05-11 11:36 UTC, bwindels commented on src/domain/session/room/timeline/MessageBodyBuilder.js
> +            if (e === "\n")
please use brackets for all block statement (this should really be in a style guide, sorry)

2021-05-11 11:36 UTC, bwindels commented on src/domain/session/room/timeline/MessageBodyBuilder.js
> +            testLink(assert, "https://matrix.org");
can we split up the tests for links and put them in `linkify.js`?

2021-05-11 11:36 UTC, bwindels commented on src/domain/session/room/timeline/linkify.js
> +    const regex = /(?:https|http|ftp):\/\/[a-zA-Z0-9:.\[\]#-]+(?:\/[^\s]*[^\s.,?!]|[^\s\u{80}-\u{10ffff}.,?!])/gui
define this at module scope so its doesn't get recreated on every invocation?

2021-05-11 11:36 UTC, bwindels commented on src/domain/session/room/timeline/linkify.js
> +    const regex = /(?:https|http|ftp):\/\/[a-zA-Z0-9:.\[\]#-]+(?:\/[^\s]*[^\s.,?!]|[^\s\u{80}-\u{10ffff}.,?!])/gui
Can we have some comments explaining the different parts of the regex?
I'm also somewhat confused by:
 - the `#` in `[a-zA-Z0-9:.\[\]#-]`, hosts can't have a `#` in them AFAIK?
 - `(?:\/[^\s]*[^\s.,?!]|[^\s\u{80}-\u{10ffff}.,?!])`, `\/[^\s]` selects /* until space, `[^\s.,?!]` selects anything but whitespace and punctuation, and why do we need `[^\s\u{80}-\u{10ffff}.,?!]` again (something related to unicode but forgot why "not whitespace" doesn't cut it)? Also, what is the operator precedence of `|` here? E.g. what does it combine? `[^\s]*[^\s.,?!]` or `[^\s.,?!]`?

2021-05-11 17:22 UTC, MidhunSureshR commented on src/domain/session/room/timeline/linkify.js
> +    const regex = /(?:https|http|ftp):\/\/[a-zA-Z0-9:.\[\]#-]+(?:\/[^\s]*[^\s.,?!]|[^\s\u{80}-\u{10ffff}.,?!])/gui
> why do we need `[^\s\u{80}-\u{10ffff}.,?!]`

If path/fragment is absent, URL must end with ASCII character.
i.e https://matrix.org🔥 -> 🔥 is not part of URL, https://matrix.org/🔥 -> 🔥 is part of URL.
AFAIK `80-10ffff` is the non-ASCII unicode range.
>Also, what is the operator precedence of | here? E.g. is the left operand `[^\s]*[^\s.,?!]` or `[^\s.,?!]`?

The left operand is  `[^\s]*[^\s.,?!]`.

2021-05-12 09:20 UTC, bwindels requested changes
Thank you for your changes! nearly there, just a few more comments about the regex.

2021-05-12 09:20 UTC, bwindels commented on src/domain/session/room/timeline/linkify/regex.js
> +const urlRegex = `${scheme}${host}+(?:${additional}|${endASCII})`;
endASCII is basically checking the last character of the hostname, right? It should have the same constraints as `host`, and additionally not accept any punctuation. This is true whether there is a path/fragment or not. So could we instead simplify to this?:
```js
const scheme = "(?:https|http|ftp):\\/\\/";
const noSpaceNorPunctuation = "[^\\s.,?!]";
const hostCharacter = "[a-zA-Z0-9:.\\[\\]-]";
// using non-consuming group here to combine two criteria for the last character
const host = `${hostCharacter}*(?=${hostCharacter})${noSpaceNorPunctuation}`;
// use sub groups so we accept just / or #, but if anything comes after it should not end with punctuation
const pathOrFragment = `(?:[\\/#](?:[^\\s]*${noSpaceNorPunctuation})?)`;
// path or fragment is optional
const urlRegex = `${scheme}${host}${pathOrFragment}?`;
```

This way the last character of the host won't accept any characters not accepted by DNS, like `https://matrix.org<`

2021-05-12 09:20 UTC, bwindels commented on src/domain/session/room/timeline/linkify/regex.js
> +/*
Thanks for splitting it up, much more readable like this!

2021-05-12 09:20 UTC, bwindels commented on src/domain/session/room/timeline/linkify/linkify.js
> +        callback(text.slice(curr, match.index), false);
perhaps assign it to a variable so it's clear what is happening? Same below.
```suggestion
        const precedingText = text.slice(curr, match.index);
        callback(precedingText, false);
```

2021-05-12 09:20 UTC, bwindels commented on src/domain/session/room/timeline/linkify/linkify.js
> +        "Link with unicode after fragment without path must linkify": assert => {
Great to have so many tests? Can we have a test for `https://matrix.org<` as well which seems to be accepted with the current regex (see below)?

2021-05-12 09:24 UTC, bwindels commented on src/domain/session/room/timeline/MessageBodyBuilder.js
> +        components.flatMap(e => ["\n", e]).slice(1).forEach(e => {
flatMap is not supported by IE11, the legacy build _should_ include a polyfill for it from corejs and put it in the legacy bundle. We should double check this is actually happening before merging.

2021-05-12 13:01 UTC, bwindels commented
I think we have a winner, will just try it out before and then merge :+1: Thanks for seeing this one out :slightly_smiling_face:

2021-05-12 13:02 UTC, bwindels approved these changes
I think we have a winner, will just try it out before and then merge :+1: Thanks for seeing this one out :slightly_smiling_face:

2021-05-12 15:40 UTC, merged